import { StyleSheet } from "react-native";

const card = StyleSheet.create({
  rock: {
    width: 360,
    height: 640,
    backgroundColor: "#B69E31",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  ghost: {
    width: 360,
    height: 640,
    backgroundColor: "#70559B",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  steel: {
    width: 360,
    height: 640,
    backgroundColor: "#B7B9D0",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  water: {
    width: 360,
    height: 640,
    backgroundColor: "#6493EB",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  grass: {
    width: 360,
    height: 640,
    backgroundColor: "#74CB48",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  psychic: {
    width: 360,
    height: 640,
    backgroundColor: "#FB5584",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  ice: {
    width: 360,
    height: 640,
    backgroundColor: "#9AD6DF",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  dark: {
    width: 360,
    height: 640,
    backgroundColor: "#75574C",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
  card: {
    width: 360,
    height: 640,
    backgroundColor: "#F9CF30",
    borderRadius: 12,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: 8,
    marginBottom: 30,
  },
});
